### ISSUE TITLE
Error when trying to make a pwned iBSS with iBSS.raw

### ISSUE THREAD

**Issue by bariscukur** [tihmstar/iBoot64Patcher#1]
main: Starting...
libc++abi.dylib: terminating with uncaught exception of type tihmstar::OFexception: std::exception
Abort trap: 6

**Comment by h3adshotzz** [comment]
You’ve decrypted the image right?

**Comment by bariscukur** [comment]
Yes but I used xpwntool to decrypt. Does it make a difference?

**Comment by h3adshotzz** [comment]
Well presumably you’re using an IM4P iBSS/iBEC image since you’re using iBoot64patcher so yes. 

Try https://github.com/xerub/img4lib to decrypt the image, then patch it. I don’t believe you can decrypt img4’s with xpwntool.

**Comment by bariscukur** [comment]
Thank you! Using img4lib to decrypt iBEC/iBSS fixed the issue.

**Comment by ireallydontwantthisaccount** [comment]
I'm still getting this error even when using img4lib to decrypt
