### ISSUE TITLE
main: Error doing patch_rsa_check()!

### ISSUE THREAD

**Issue by danieltroger** [tihmstar/iBoot64Patcher#13]
my ibss (coming from iBSS.n69.RELEASE.im4p, iOS 13.5, iPhone SE) is for sure decrypted (using img4):
```
daniel@Daniels-iMac:~/Documents/dualbootfun/working_dir/Firmware/dfu$ strings iBSS.dec
iBootStage1 for n69, Copyright 2007-2019, Apple Inc.
RELEASE
iBoot-5540.120.17
uuid
```
# The error is this:
```
daniel@Daniels-iMac:~/Documents/dualbootfun/working_dir/Firmware/dfu$ iBoot64Patcher iBSS.dec iBSS.patched
main: Starting...
getting get_sigcheck_patch() patch
main: Error doing patch_rsa_check()!
```

I have traced it back to this line throwing an error: https://github.com/tihmstar/iBoot64Patcher/blob/master/iBoot64Patcher/main.cpp#L106
and apparently this is called first: https://github.com/tihmstar/liboffsetfinder64/blob/master/liboffsetfinder64/ibootpatchfinder64.cpp#L141
which then throws an error: `reterror("not implemented by provider");`

Please help, I just want to boot a fucking ramdisk so I can figure out if I can delete files through that to make an iPhone that's not booting due to `No space left on device` boot. Is 13.5 not supported by iBoot64Patcher? Is it confusing iBSS with iOS 14? I tried to revert both repos to Jun and Jan pre ios 14 commits but it didn't help.

Why is nothing implemented by provider? In [this file](https://github.com/tihmstar/liboffsetfinder64/blob/master/liboffsetfinder64/ibootpatchfinder64_base.cpp) the functions exist but they don't get called for some reason

**Comment by danieltroger** [comment]
In case anyone also has this issue, iBoot64Patcher doesn't seem to be compatible with iOS 13 for both iPhone X and iPhone SE. 12.4.1 works

**Comment by LetsUnlockiPhone** [comment]
I have the same problem with ibridge image. Have you solved this issue Daniel?

**Comment by danieltroger** [comment]
Yes! Use kairos instead, this tool is basically outdated. https://github.com/dayt0n/kairos

Also, shameless plug, if you're trying to load a ramdisk I made a tool for that with what I learned: https://github.com/danieltroger/telnetd_ramdisk/blob/master/make_telnet_rd.php

**Comment by LetsUnlockiPhone** [comment]
Perfect, thanks a lot Daniel. trying that now
