### ISSUE TITLE
 It can't set iphone8's ibec boot-args.

### ISSUE THREAD

**Issue by CoreNion** [tihmstar/iBoot64Patcher#7]
When I Execute ` ./iBoot64Patcher ibec.raw ibec.pwn -b -v`, iBootpatcher says `main: Error doing patch_boot_args()` ....
Other device's ibec Doesn't have it error.
Of course I decrypt ibec. And no option can patch.

**Comment by Halo-Michael** [comment]
Same on iPhone9,1(iPhone7), iOS13.3.1b1

**Comment by mattso-exe** [comment]
try this:
./iBoot64Patcher ibec.raw ibec.pwn -b "-v"

**Comment by CoreNion** [comment]
The latest version of liboffsetfinder64 seems to have solved the problem.

**Comment by CoreNion** [comment]
I accidentally put up an issue by a private account, can @tihmstar delete this issue?

Because if my acquaintance find it, I have problem.
