### ISSUE TITLE
Undefined symbol

### ISSUE THREAD

**Issue by justtryingthingsout** [tihmstar/iBoot64Patcher#9]
While compiling on Xcode,  it gives an error saying `Undefined symbol: typeinfo for tihmstar::exception`. The full error is `Undefined symbols for architecture x86_64:
  "typeinfo for tihmstar::exception", referenced from:
      GCC_except_table0 in main.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
`

**Comment by Merculous** [comment]
Figured it out. All you need to do is open the xcode project and add libgeneral where the liboffsetfinder64.dylib is located. You can find the libgeneral.dylib in /usr/local/lib Have fun!

**Comment by Halo-Michael** [comment]
> Figured it out. All you need to do is open the xcode project and add libgeneral where the liboffsetfinder64.dylib is located. You can find the libgeneral.dylib in /usr/local/lib Have fun!

Thanks!

**Comment by justtryingthingsout** [comment]
Thanks, will close the issue.
